// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoRepuestos.Services;

#nullable disable

namespace ProyectoRepuestos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250920041046_UpdateSeeder2")]
    partial class UpdateSeeder2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoRepuestos.Models.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Repuestos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del Repuesto1",
                            IsActive = true,
                            Name = "Repuesto1",
                            Price = 100m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del Repuesto2",
                            IsActive = true,
                            Name = "Repuesto2",
                            Price = 200m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Descripción del Repuesto3",
                            IsActive = true,
                            Name = "Repuesto3",
                            Price = 300m,
                            StockQuantity = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
